### ISSUE TITLE
upgrading to 0.41.0 results in TypeError: args.slice is not a function

### ISSUE THREAD

**Issue by gabrielgrant** [kellyselden/ember-awesome-macros#448]
When using 0.34.0 my app loads fine. When upgrading to 0.41.0, trying to load the app results in `TypeError: args.slice is not a function` on my index route

Full traceback:

```
Error while processing route: app.index args.slice is not a function TypeError: args.slice is not a function
    at parseComputedArgs (http://127.0.0.1:4200/assets/vendor.js:172540:18)
    at exports.default (http://127.0.0.1:4200/assets/vendor.js:172575:30)
    at Module.callback (http://127.0.0.1:4200/assets/vendor.js:172983:48)
    at Module.exports (http://127.0.0.1:4200/assets/vendor.js:111:32)
    at Module._reify (http://127.0.0.1:4200/assets/vendor.js:148:59)
    at Module.reify (http://127.0.0.1:4200/assets/vendor.js:135:27)
    at Module.exports (http://127.0.0.1:4200/assets/vendor.js:109:10)
    at Module._reify (http://127.0.0.1:4200/assets/vendor.js:148:59)
    at Module.reify (http://127.0.0.1:4200/assets/vendor.js:135:27)
    at Module.exports (http://127.0.0.1:4200/assets/vendor.js:109:10)
ember-metal.js:3988 TypeError: args.slice is not a function
    at parseComputedArgs (-build-computed.js:6)
    at exports.default (-build-computed.js:41)
    at Module.callback (lazy-computed.js:7)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
```

![screenshot from 2018-03-04 07 34 20](https://user-images.githubusercontent.com/493968/36947641-d5f3dcd6-1f83-11e8-8e82-3aeb3884fb34.png)

![screenshot from 2018-03-04 08 13 57](https://user-images.githubusercontent.com/493968/36948755-749fe4aa-1f94-11e8-9280-ff9a084e7eff.png)
![screenshot from 2018-03-04 08 13 42](https://user-images.githubusercontent.com/493968/36948758-7dc9eed6-1f94-11e8-986e-7c573200e9a6.png)

Debugger confirms that args is an object, not an array: 

![screenshot from 2018-03-05 09 43 06](https://user-images.githubusercontent.com/493968/36990490-baeaeab6-2059-11e8-9214-adbf74c4ac36.png)

...which seems to originate in `lazy-computed.js`:

![screenshot from 2018-03-05 09 44 51](https://user-images.githubusercontent.com/493968/36990584-03d9a762-205a-11e8-8715-1780a968d435.png)

... where it gets passed to build-computed.js

![screenshot from 2018-03-05 09 46 26](https://user-images.githubusercontent.com/493968/36990616-2335f426-205a-11e8-91fe-f4a9836284d2.png)

**Comment by kellyselden** [comment]
If this is still an issue, please post back.
